services:
  redis:
    image: redis:latest
    container_name: pokemon-redis
    ports:
      - "6379:6379"
    networks:
      - pokemon-network

  app:
    build: .
    container_name: pokemon-app
    ports:
      - "8808:8808" 
    depends_on:
      - redis
    networks:
      - pokemon-network
    environment:
      - REDIS_HOST=pokemon-redis  # Nombre del servicio de Redis en Docker

networks:
  pokemon-network:
    driver: bridge


